List<String> quotes = [
  "Your life has value, and you are worthy of love and support.",
  "Strength comes from overcoming adversity. You are stronger than you think.",
  "You have the power to create a positive change in your life.",
  "Believe in yourself, even when it feels impossible.",
  "Every day is a new opportunity to heal and grow.",
  "You are not alone; there are people who care about you.",
  "Your mental illness does not define your worth or potential.",
  "Healing takes time, and that's okay. Be patient with yourself.",
  "You are resilient. You've already survived every bad day so far.",
  "Your future is filled with possibilities and opportunities.",
  "It's okay to ask for help; it's a sign of strength, not weakness.",
  "You are loved, even on your darkest days.",
  "Your story is important and can inspire others.",
  "Recovery is a journey, and every step forward is a victory.",
  "You are more than your mental illness; you are unique and valuable.",
  "Hope is the anchor of the soul. Keep hope alive.",
  "Your presence in this world makes a difference.",
  "You are worthy of self-compassion and self-care.",
  "Embrace self-acceptance; you are enough just as you are.",
  "Your struggles do not define your worth.",
  "You are a work in progress, and progress is beautiful.",
  "The pain you're feeling today won't last forever.",
  "Your mind is powerful, and you have the strength to change it.",
  "You are not your thoughts; you can choose what you focus on.",
  "Celebrate your small victories; they lead to big ones.",
  "There is light at the end of the tunnel; keep moving forward.",
  "You are capable of facing your fears and challenges.",
  "Your worth is not determined by external validation.",
  "Take each day one step at a time; progress is cumulative.",
  "Your uniqueness is what makes you special.",
  "It's okay to take breaks and rest when needed.",
  "You have the potential to inspire and help others.",
  "You are a survivor, and survivors are warriors.",
  "Your past does not define your future.",
  "Believe in the power of positive thinking.",
  "You have the inner strength to overcome any obstacle.",
  "Your life has meaning, even in moments of darkness.",
  "Stay committed to your healing journey; it's worth it.",
  "You are a masterpiece in progress.",
  "Remember, you are loved, even when it doesn't feel like it.",
  "You are not alone in your struggles; others understand.",
  "Self-care is not selfish; it's essential for your well-being.",
  "Your emotions are valid; it's okay to feel what you feel.",
  "Your mental health matters; prioritize it.",
  "You have the power to rewrite your story.",
  "You are capable of creating a life filled with happiness.",
  "Take a deep breath and focus on the present moment.",
  "You are never given more than you can handle.",
  "Your strength is greater than your challenges.",
  "You are a fighter, and fighters don't give up.",
  "Trust in the journey; the path may be uncertain, but it's worth it.",
  "You have the resilience to bounce back from setbacks.",
  "Your voice matters; speak your truth.",
  "Believe in the potential for change and growth.",
  "You are not defined by your mistakes; they are opportunities to learn.",
  "Celebrate your progress, no matter how small it may seem.",
  "You are not alone in your battles; there is a community of support.",
  "Your heart is stronger than your mind sometimes; listen to it.",
  "Believe in your ability to find joy and purpose.",
  "You are never too broken to heal and rebuild.",
  "Your journey may be difficult, but it's uniquely yours.",
  "Embrace the power of self-compassion and forgiveness.",
  "You have the strength to face your fears head-on.",
  "Your potential for happiness is limitless.",
  "You are the author of your story; write a beautiful one.",
  "Remember that setbacks are just setups for comebacks.",
  "You have the courage to stand up to your inner critic.",
  "Your inner peace is worth the effort to find.",
  "Believe in the process of healing; it's not always linear.",
  "You are a survivor, and survivors thrive.",
  "Your journey is a testament to your strength.",
  "You are not defined by your scars; they are a part of your story.",
  "Celebrate the small moments of joy in life.",
  "You are a beacon of hope for those who know you.",
  "Your future holds brighter days, even if you can't see them yet.",
  "Believe in your ability to create positive change.",
  "You have the power to transform pain into strength.",
  "Your inner resilience is a force to be reckoned with.",
  "Remember to practice self-love; you are deserving of it.",
  "You are the captain of your ship; steer it toward happiness.",
  "Your strength shines through your vulnerability.",
  "Celebrate your uniqueness; it's what makes you extraordinary.",
  "You are deserving of love, both from others and yourself.",
  "Believe in the possibility of a brighter tomorrow.",
  "Your life is a canvas; paint it with love and hope.",
  "You have the courage to break free from negative patterns.",
  "Your heart is capable of tremendous love and compassion.",
  "Remember that you are a survivor, not a victim.",
  "You are the driver of your destiny; choose the path of healing.",
  "Your challenges are opportunities for growth and transformation.",
  "Believe in your ability to rise above adversity.",
  "You are a warrior of the mind, body, and spirit.",
  "Your journey toward healing is a brave and courageous one.",
  "You have the strength to turn your pain into purpose.",
  "Your story is a testament to your resilience and courage.",
  "Remember that hope is always within reach, even in the darkest moments.",
  "You are not defined by your scars, but by the strength it took to heal them.",
  "Believe in the power of self-compassion and self-acceptance.",
  "You are not alone on this journey; there is a community that cares.",
  "Your inner light can shine even in the midst of darkness.",
  "You have the strength to rise above your challenges.",
  "Your journey may be difficult, but it's forging your character.",
  "Remember to be kind to yourself; you deserve it.",
  "You are capable of finding beauty in the broken pieces.",
  "Believe in your ability to overcome any obstacle.",
  "You are not your past; you are the present and the future.",
  "Your potential for happiness is boundless.",
  "You have the power to rewrite your story with hope and resilience.",
  "Remember that setbacks are opportunities for comebacks.",
  "You are strong enough to silence your inner critic.",
  "Your inner peace is worth the pursuit.",
  "Believe in the journey of healing, no matter how challenging.",
  "You are a survivor, and survivors thrive.",
  "Your strength is a testament to your resilience and determination.",
  "You are not defined by your scars; they are reminders of your strength.",
  "Celebrate the small victories on your path to recovery.",
  "You are a source of inspiration for those around you.",
  "Your future holds the promise of brighter days.",
  "Believe in your power to create positive change.",
  "You have the ability to transform pain into strength.",
  "Your inner resilience is a powerful force.",
  "Remember to practice self-love and self-acceptance.",
  "You are the captain of your life's journey; steer it toward happiness.",
  "Your strength shines brightly through vulnerability.",
  "Celebrate your uniqueness; it sets you apart.",
  "You are deserving of love and kindness, both from others and yourself.",
  "Believe in the possibility of a brighter tomorrow.",
  "You have the courage to break free from negative patterns.",
  "Your heart is capable of boundless love and compassion.",
  "Remember that you are a survivor, not a victim.",
  "You are in control of your destiny; choose the path of healing.",
  "Your challenges are opportunities for growth and transformation.",
  "Believe in your ability to rise above adversity.",
  "You are a warrior of the mind, body, and spirit.",
  "Your journey toward healing is a brave and courageous one.",
  "You have the strength to turn pain into purpose.",
  "Your story is a testament to your resilience and courage.",
  "Remember that hope is always within reach, even in the darkest moments.",
  "You are not defined by your scars, but by the strength it took to heal them.",
  "Believe in the power of self-compassion and self-acceptance.",
  "You are not alone on this journey; there is a community that cares.",
  "Your inner light can shine even in the midst of darkness.",
  "You have the strength to rise above your challenges.",
  "Your journey may be difficult, but it's forging your character.",
  "Remember to be kind to yourself; you deserve it.",
  "You are capable of finding beauty in the broken pieces.",
  "Believe in your ability to overcome any obstacle.",
  "You are not your past; you are the present and the future.",
  "Your potential for happiness is boundless.",
  "You have the power to rewrite your story with hope and resilience.",
  "Remember that setbacks are opportunities for comebacks.",
  "You are strong enough to silence your inner critic.",
  "Your inner peace is worth the pursuit.",
  "Believe in the journey of healing, no matter how challenging.",
  "You are a survivor, and survivors thrive.",
  "Your strength is a testament to your resilience and determination.",
  "You are not defined by your scars; they are reminders of your strength.",
  "Celebrate the small victories on your path to recovery.",
  "You are a source of inspiration for those around you.",
  "Your future holds the promise of brighter days.",
  "Believe in your power to create positive change.",
  "You have the ability to transform pain into strength.",
  "Your inner resilience is a powerful force.",
  "Remember to practice self-love and self-acceptance.",
  "You are the captain of your life's journey; steer it toward happiness.",
  "Your strength shines brightly through vulnerability.",
  "Celebrate your uniqueness; it sets you apart.",
  "You are deserving of love and kindness, both from others and yourself.",
  "Believe in the possibility of a brighter tomorrow.",
  "You have the courage to break free from negative patterns.",
  "Your heart is capable of boundless love and compassion.",
  "Remember that you are a survivor, not a victim."
];